export const PrivacyPolicyData = {
  privacyPolicy: {
    title: "Privact Policy",
    date: "Effective Date April 30,2023",
    discription: `Welcome to Fashion Minis. R.K. Garments Pvt. Ltd. ("us", "we", or "our") operates the fashionminis.io store and the Synergy application (herein after referred to as the "Service"). Our Privacy Policy explains how we collect, use, disclose, and protect information that applies to our Service, and your choices about the collection and use of your information. This policy sets out how Synergy collects and uses the information that we collect about you when you use the Synergy services. This policy also explains the choices that you can make about the way that we use your information.`,
  },
  definitions: {
    title: "Definitions",
    definitions: [
      {
        heading: "Personal Data",
        discription:
          "Personal Data means data about a living individual who can be identified from those data.",
      },
      {
        heading: "Usage Data",
        discription:
          "Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.",
      },
      {
        heading: "Cookies",
        discription:
          "Cookies are small pieces stored on your device (computer or mobile device).",
      },
    ],
  },
  information: {
    title: "Information we collect and its us",
    subTitle: "We collect the following types of information about you",
    definitions: [
      {
        heading: "Information you provide us directly",
        discription: `While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include Email Address, Phone Number, Business Name, First and Last Name, Cookies and Usage Data.`,
      },
      {
        heading: "Usage Data",
        discription: `We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
          When using our service, we may ask you to provide us some permissions to measure key metrics across other apps and websites.`,
      },
      {
        heading: "Cookies Information",
        discription: `Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.`,
      },
    ],
  },
};
